AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5

Resources:
  Test202212PreSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: PreSignup.do
      Runtime: python3.7
      Architectures:
        - x86_64
  Test202212DefineAuthChallengeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: DefineAuthChallenge.do
      Runtime: python3.7
      Architectures:
        - x86_64
  Test202212CreateAuthChallengeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: CreateAuthChallenge.do
      Runtime: python3.7
      Architectures:
        - x86_64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: "*"
  Test202212VerifyAuthChallengeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: VerifyAuthChallenge.do
      Runtime: python3.7
      Architectures:
        - x86_64
  Test202212PreSignupFunctionInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt Test202212PreSignupFunction.Arn
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt Test202212CognitoUserPool.Arn
  Test202212DefineAuthChallengeFunctionInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt Test202212DefineAuthChallengeFunction.Arn
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt Test202212CognitoUserPool.Arn
  Test202212CreateAuthChallengeFunctionInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt Test202212CreateAuthChallengeFunction.Arn
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt Test202212CognitoUserPool.Arn
  Test202212VerifyAuthChallengeFunctionInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt Test202212VerifyAuthChallengeFunction.Arn
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt Test202212CognitoUserPool.Arn
  Test202212CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      Schema:
        - Name: locale
          AttributeDataType: String
          Mutable: true
          Required: false
      UsernameConfiguration:
        CaseSensitive: false
      LambdaConfig:
        PreSignUp: !GetAtt Test202212PreSignupFunction.Arn
        DefineAuthChallenge: !GetAtt Test202212DefineAuthChallengeFunction.Arn
        CreateAuthChallenge: !GetAtt Test202212CreateAuthChallengeFunction.Arn
        VerifyAuthChallengeResponse: !GetAtt Test202212VerifyAuthChallengeFunction.Arn
  Test202212CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      "Domain": test202212
      "UserPoolId": !Ref Test202212CognitoUserPool
  Test202212CognitoUserPoolAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref Test202212CognitoUserPool
      ClientName: Test202212_appclient
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:12500/
      LogoutURLs:
        - http://localhost:12500/
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
  Test202212ParameterEmailFromAddress:
    Type: AWS::SSM::Parameter
    Properties:
      Description: 'From email address used to send the challenge'
      Name: !Join
        - ''
        - - 'be.tetram.cognito.passwordfree.'
          - !Ref Test202212CognitoUserPool
          - '.mailFromAddress'
      Tier: 'Intelligent-Tiering'
      Type: 'String'
      Value: 'sender@example.com'
  Test202212ParameterEmailTitleEn:
    Type: AWS::SSM::Parameter
    Properties:
      Description: 'English version of the challenge mail title'
      Name: !Join
        - ''
        - - 'be.tetram.cognito.passwordfree.'
          - !Ref Test202212CognitoUserPool
          - '.en.mailTitle'
      Tier: 'Intelligent-Tiering'
      Type: 'String'
      Value: 'Your confirmation code is $code'
  Test202212ParameterEmailBodyEn:
    Type: AWS::SSM::Parameter
    Properties:
      Description: 'English text version of the challenge mail body'
      Name: !Join
        - ''
        - - 'be.tetram.cognito.passwordfree.'
          - !Ref Test202212CognitoUserPool
          - '.en.mailBody'
      Tier: 'Intelligent-Tiering'
      Type: 'String'
      Value: "Your confirmation code is $code. \n Copy it in the authentication interface to confirm your email address."
  Test202212ParameterEmailBodyHtmlEn:
    Type: AWS::SSM::Parameter
    Properties:
      Description: 'English html version of the challenge mail body'
      Name: !Join
        - ''
        - - 'be.tetram.cognito.passwordfree.'
          - !Ref Test202212CognitoUserPool
          - '.en.mailBodyHtml'
      Tier: 'Intelligent-Tiering'
      Type: 'String'
      Value: "<html><body><p>Your confirmation code is $code.</p><h3>$code</h3><p>Copy it in the authentication interface to confirm your email address.</body></html>"
  Test202212ParameterEmailTitleFr:
    Type: AWS::SSM::Parameter
    Properties:
      Description: 'French version of the challenge mail title'
      Name: !Join
        - ''
        - - 'be.tetram.cognito.passwordfree.'
          - !Ref Test202212CognitoUserPool
          - '.fr.mailTitle'
      Tier: 'Intelligent-Tiering'
      Type: 'String'
      Value: 'Votre code de confirmation est $code'
  Test202212ParameterEmailBodyFr:
    Type: AWS::SSM::Parameter
    Properties:
      Description: 'French text version of the challenge mail body'
      Name: !Join
        - ''
        - - 'be.tetram.cognito.passwordfree.'
          - !Ref Test202212CognitoUserPool
          - '.fr.mailBody'
      Tier: 'Intelligent-Tiering'
      Type: 'String'
      Value: "Votre code de confirmation est $code. \n Recopiez-le dans l'interface d'authentification pour confirmer votre adresse e-mail."
  Test202212ParameterEmailBodyHtmlFr:
    Type: AWS::SSM::Parameter
    Properties:
      Description: 'French html version of the challenge mail body'
      Name: !Join
        - ''
        - - 'be.tetram.cognito.passwordfree.'
          - !Ref Test202212CognitoUserPool
          - '.fr.mailBodyHtml'
      Tier: 'Intelligent-Tiering'
      Type: 'String'
      Value: "<html><body><p>Votre code de confirmation est $code.</p><h3>$code</h3><p>Recopiez-le dans l'interface d'authentification pour confirmer votre adresse e-mail.</body></html>"
